# -*- coding: utf-8 -*-
"""
/***************************************************************************
 changeAttribut
                                 A QGIS plugin.
 plugin de contribution directe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-28
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from datetime import datetime
import locale

# from networkx.algorithms.isomorphism.matchhelpers import close
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QPushButton, QLabel,QApplication

from qgis.core import Qgis, QgsExpression

# Import the code for the dialog
from .change_attribut_hydro_dialog import changeAttributDialog
from .aproposde import Aproposde
from .editIDPE import EditIDPE
from .editIDBCAE import EditIDBCAE
import os.path

from .constante import *
from .fonction import *
from .cheminpluscourt import *


# recuperation de l'id de la transaction (à partir du plugin espace co)
def getidtransaction():
    from qgis.utils import plugins
    idtransaction = None
    try:
        processing_plugin = plugins[PLUGIN_ESPACE_CO]
        try:
            idtransaction = processing_plugin.getlibelletransaction()
        except AttributeError:
            idtransaction = "Récuperation en cours de développement"
    except KeyError:
        print("plugin non chargé")

    if idtransaction is None:
        return "Pas de transaction vers la BDUNI (travail hors ligne)"
    else:
        return idtransaction


class changeAttribut:
    """QGIS Plugin Implementation."""

    def set_activeLayerHydro(self):
        project = QgsProject.instance()
        layer = project.mapLayersByName(LAYER_HYDRO)
        # afficheerreur(layer[0].name())
        if not layer:
            return False
        else:
            self.iface.setActiveLayer(layer[0])
            return True

    def runchepluscourt(self):
        self.cheminpluscourt.cheminpluscourt()
        # réactivation du layer route apres traitement
        self.set_activeLayerHydro()
        # zoom sur la selection
        self.iface.actionZoomToSelected().trigger()

    def afficheAProposeDe(self):
        self.dlgAProposDe.show()

    def afficheDialEditIdPE(self):
        self.dlgEditIdPE.setWindowFlags(Qt.WindowStaysOnTopHint)
        self.dlgEditIdPE.lineEditEditPE.setText(self.dlg.lineEditIdPE.text())
        self.dlgEditIdPE.setWindowModality(Qt.ApplicationModal)
        self.dlgEditIdPE.show()

    def afficheDialEditIdBCAE(self):
        self.dlgEditIdBCAE.setWindowFlags(Qt.WindowStaysOnTopHint)
        self.dlgEditIdBCAE.lineEditEditBCAE.setText(self.dlg.lineEditIdBCAE.text())
        self.dlgEditIdBCAE.setWindowModality(Qt.ApplicationModal)
        self.dlgEditIdBCAE.show()


    def recup_id_pe(self):
        idpe_avant_modif = self.dlg.lineEditIdPE.text()
        self.dlg.lineEditIdPE.setText(self.dlgEditIdPE.lineEditEditPE.text())
        self.dicoAttributs[ID_PE] = self.dlg.lineEditIdPE.text()
        self.dlgEditIdPE.close()
        if idpe_avant_modif != self.dlgEditIdPE.lineEditEditPE.text():
            self.dlg.lineEditIdPE.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            # self.isAttributsmodifiy = True
        else:
            self.dlg.lineEditIdPE.setStyleSheet(CUSTOM_WIDGETS[1])

    def recup_id_bcae(self):
        idbcae_avant_modif = self.dlg.lineEditIdBCAE.text()
        self.dlg.lineEditIdBCAE.setText(self.dlgEditIdBCAE.lineEditEditBCAE.text())
        self.dicoAttributs[ID_BCAE] = self.dlg.lineEditIdBCAE.text()
        self.dlgEditIdBCAE.close()
        if idbcae_avant_modif != self.dlgEditIdBCAE.lineEditEditBCAE.text():
            self.dlg.lineEditIdBCAE.setStyleSheet(CUSTOM_WIDGETS[0])
            self.dlg.pushButtonValiderTransaction.setEnabled(True)
            # self.isAttributsmodifiy = True
        else:
            self.dlg.lineEditIdBCAE.setStyleSheet(CUSTOM_WIDGETS[1])

    def ferme_dial(self):
        self.dlgEditIdPE.close()
        self.dlgEditIdBCAE.close()

    def colorchange(self):
        self.actualiserSelection()

    def natureCanal(self):
        if self.nbselection == 0:
            return

        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listbtnNature, "pushButtonNatureCanal")
        self.dicoAttributs[NATURE] = "Canal"

        self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def natureConduitBuse(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listbtnNature, "pushButtonNatureConduitBuse")
        self.dicoAttributs[NATURE] = "Conduit buse"
        self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def natureEcoulNat(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listbtnNature, "pushButtonNatureEcoulNat")
        self.dicoAttributs[NATURE] = "Ecoulement naturel"
        self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def comboboxNatureChange(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listbtnNature, "comboBoxNature")
        self.dicoAttributs[NATURE] = self.dlg.comboBoxNature.currentText()
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def possolmoins1(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listbtnpossol, "pushButtonPosSolm1")
        # ajout des données dans un dictionnaire pout gérer une seule transaction à la fin
        self.dicoAttributs[POS_SOL] = "-1"
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def possol0(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listbtnpossol, "pushButtonPosSol0")
        # ajout des données dans un dictionnaire pout gérer une seule transaction à la fin
        self.dicoAttributs[POS_SOL] = "0"
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def possol1(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listbtnpossol, "pushButtonPosSol1")
        # ajout des données dans un dictionnaire pout gérer une seule transaction à la fin
        self.dicoAttributs[POS_SOL] = "1"
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def invPEVrai(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listInvPE, "pushButtonInventPEVrai")
        # ajout des données dans un dictionnaire pout gérer une seule transaction à la fin
        self.dicoAttributs[INVENT_PE] = "Inscrit"
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def invPEFaux(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listInvPE, "pushButtonInventPEFaux")
        # ajout des données dans un dictionnaire pout gérer une seule transaction à la fin
        self.dicoAttributs[INVENT_PE] = "Non inscrit"
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def invPEEnCours(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listInvPE, "pushButtonInventPEEnCours")
        # ajout des données dans un dictionnaire pout gérer une seule transaction à la fin
        self.dicoAttributs[INVENT_PE] = EXPERTENCOURS
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def invBCAEVrai(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listInvBCAE, "pushButtonInventBCAEVrai")
        # ajout des données dans un dictionnaire pout gérer une seule transaction à la fin
        self.dicoAttributs[INVENT_BCAE] = 1
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    def invBCAEFaux(self):
        if self.nbselection == 0:
            return
        # self.isAttributsmodifiy = True
        self.initbtnclic(self.listInvBCAE, "pushButtonInventBCAEFaux")
        # ajout des données dans un dictionnaire pout gérer une seule transaction à la fin
        self.dicoAttributs[INVENT_BCAE] = 0
        self.dlg.pushButtonValiderTransaction.setEnabled(True)

    # def fineditionidentPE(self):
    #     self.dlg.pushButtonNatureCanal.setFocus()
    #     # if self.nbselection == 0: return
    #     # self.dicoAttributs[ID_PE] = self.dlg.lineEditIdPE.text()
    #     # # self.dlg.lineEditIdPE.setStyleSheet(CUSTOM_WIDGETS[0])
    #     # self.dlg.pushButtonValiderTransaction.setEnabled(True)

    # def textchangeidentPE(self):
    #     # if self.nbselection == 0: return
    #     # self.dicoAttributs[ID_PE] = self.dlg.lineEditIdPE.text()
    #     # self.dlg.lineEditIdPE.setStyleSheet(CUSTOM_WIDGETS[0])
    #     # self.dlg.pushButtonValiderTransaction.setEnabled(True)
    #     pass

    # def returnpressIdPE(self):
    #     afficheerreur("returnpressIdPE")
    #     # self.dlg.pushButtonPosSol1.setFocus()
    #
    #
    # def fineditionidentBCAE(self):
    #     if self.nbselection == 0: return
    #     self.dicoAttributs[ID_BCAE] = self.dlg.lineEditIdBCAE.text()
    #     self.dlg.pushButtonValiderTransaction.setEnabled(True)
    #
    # def textchangeidentBCAE(self):
    #     self.dlg.lineEditIdBCAE.setStyleSheet(CUSTOM_WIDGETS[0])


    def initbtnclic(self, listgroupebtn, btnclick=""):
        # TODO : initbtnclic

        # combobox nature à faire avant les autres boutons
        if btnclick == self.dlg.comboBoxNature.objectName():
            # print(btnclick + " -- " + self.dlg.comboBoxNature.objectName())
            self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[0])

        for i, btn in enumerate(self.dlg.findChildren(QPushButton)):
            # juste les boutons de l'interface correspondant à la list de boutons passé en parametre
            if btn.objectName() in listgroupebtn:
                # 2 : pas de fond
                btn.setStyleSheet(CUSTOM_WIDGETS[2])
                if btnclick == btn.objectName():
                    # 0 : fond bleu
                    btn.setStyleSheet(CUSTOM_WIDGETS[0])
                    # fond par defaut pour le combobox

    def afficheMessageBar(self, message):
        self.iface.messageBar().pushMessage("Info", message, level=Qgis.Info, duration=5)

    def validerLaTransaction(self):

        # TODO validerLaTransaction
        # on sauvegarde la selection avant les modifs parce que le commitchanges vide la selection
        self.selectiontotal = self.listeSelection

        if len(self.dicoAttributs) == 0:
            return

        self.layer.startEditing()

        ischange = False
        locale.setlocale(locale.LC_TIME, 'fr_FR')

        for selection in self.listeSelection:
            attr = selection.attributes()
            for cle in self.dicoAttributs:
                idchamps = self.layer.fields().indexFromName(cle)
                # on ne modifie que si l'attribut a vraiment changé
                # TODO a faire : si different ou "vide" on modifie pas
                if str(attr[idchamps]) != str(self.dicoAttributs[cle]):
                    ischange = True
                    self.layer.changeAttributeValue(selection.id(), idchamps, str(self.dicoAttributs[cle]))

        self.afficheMessageBar(f"Les modifications ont été effectués sur : {self.nbselection} objet(s)")

        self.dicoAttributs.clear()

    def initialiselabel(self):
        # fond gris
        for i, label in enumerate(self.dlg.findChildren(QLabel)):
            if (label.objectName() != "labeltext" and
                    label.objectName() != "labelNbSelection" and
                    label.objectName() != "labelCoulSel"):
                label.setStyleSheet(CUSTOM_WIDGETS[3])

        self.dlg.lineEditIdPE.setStyleSheet(CUSTOM_WIDGETS[2])
        self.dlg.lineEditIdBCAE.setStyleSheet(CUSTOM_WIDGETS[2])

    def afficheAttribut(self):
        # TODO : afficheAttribut

        self.dlg.lineEditCleabs.setText("")
        self.dlg.lineEditToponyme.setText("")
        self.dlg.lineEditIdPE.setText("")
        self.dlg.lineEditIdBCAE.setText("")
        # on affiche les attributes que si un seul troncon est selectionné
        if self.nbselection != 1:
            return

        attr = self.listeSelection[0].attributes()

        """************** CLEABS ******************************"""
        self.dlg.lineEditCleabs.setText(attr[self.idcleabs])

        """************** CPX_TOPONYME ******************************"""
        self.dlg.lineEditToponyme.setText(attr[self.idtoponyme])

        """************** NATURE*******************************"""
        if attr[self.idnature] == "Canal":
            self.dlg.pushButtonNatureCanal.setStyleSheet(CUSTOM_WIDGETS[1])
            self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[2])

        elif attr[self.idnature] == "Conduit buse":
            self.dlg.pushButtonNatureConduitBuse.setStyleSheet(CUSTOM_WIDGETS[1])
            self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[2])
        elif attr[self.idnature] == "Ecoulement naturel":
            self.dlg.pushButtonNatureEcoulNat.setStyleSheet(CUSTOM_WIDGETS[1])
            self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[2])
        else:
            self.dlg.comboBoxNature.setCurrentText(attr[self.idnature])
            self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[1])

        """************** POSITION SOL ************************"""
        if attr[self.idposol] == "-1":
            # self.dlg.pushButtonPosSolm1.setChecked(True)
            self.dlg.pushButtonPosSolm1.setStyleSheet(CUSTOM_WIDGETS[1])
        elif attr[self.idposol] == "0":
            self.dlg.pushButtonPosSol0.setStyleSheet(CUSTOM_WIDGETS[1])
        elif attr[self.idposol] == "1":
            self.dlg.pushButtonPosSol1.setStyleSheet(CUSTOM_WIDGETS[1])

        """************** INVENTAIRE PE ************************"""
        if attr[self.idinventairePE] == "Inscrit":
            self.dlg.pushButtonInventPEVrai.setStyleSheet(CUSTOM_WIDGETS[1])
        elif attr[self.idinventairePE] == "Non inscrit":
            self.dlg.pushButtonInventPEFaux.setStyleSheet(CUSTOM_WIDGETS[1])
        elif attr[self.idinventairePE] == EXPERTENCOURS:
            self.dlg.pushButtonInventPEEnCours.setStyleSheet(CUSTOM_WIDGETS[1])
        # else:
        #     self.dlg.pushButtonInventPEEnCours.setStyleSheet(CUSTOM_WIDGETS[1])

        """************** INVENTAIRE BCAE ************************"""
        if attr[self.idinventaireBCAE] == 1:
            self.dlg.pushButtonInventBCAEVrai.setStyleSheet(CUSTOM_WIDGETS[1])
        elif attr[self.idinventaireBCAE] == 0:
            self.dlg.pushButtonInventBCAEFaux.setStyleSheet(CUSTOM_WIDGETS[1])

        """************** ID PE ************************"""
        self.dlg.lineEditIdPE.setText(attr[self.idpe])
        self.dlg.lineEditIdPE.setStyleSheet(CUSTOM_WIDGETS[1])

        """************** ID BCAE ************************"""
        self.dlg.lineEditIdBCAE.setText(attr[self.idbcae])
        self.dlg.lineEditIdBCAE.setStyleSheet(CUSTOM_WIDGETS[1])

    def actualiserSelection(self):
        # TODO : actualiserSelection
        print("actualiserSelection HYDRO")

        if not self.set_activeLayerHydro():
            afficheerreur(f"La couche \"{LAYER_HYDRO}\" n'est pas activée.\nSi l'assistant de contribution direct hydro est ouvert il faut le fermer",TITRE_INTERFACE)

            return
        else:
            self.layer = self.iface.activeLayer()

        couleur = self.dlg.mColorButton.color()
        self.iface.mapCanvas().setSelectionColor(couleur)


        self.listeSelection = self.layer.selectedFeatures()
        self.nbselection = self.layer.selectedFeatureCount()
        self.dlg.labelNbSelection.setText(str(self.nbselection))
        # activation du btn qui s'il y a un changement d'attributs
        self.dlg.pushButtonValiderTransaction.setEnabled(False)

        # if self.isAttributsmodifiy:
        #     afficheerreur("Vous n'avez pas validez les modifications", "Attention...")
        #     self.isAttributsmodifiy = False
        #     return


        if self.nbselection == 1:
            # on initialise tous les btn avant de faire affciheAttribut
            self.initbtnclic(self.listBtnTotal)
            self.afficheAttribut()
            self.dlg.pushButtonPlusCourt.setEnabled(False)

        elif self.nbselection == 2:
            # tous les btn avec fond par defaut
            self.dlg.lineEditCleabs.setText("")
            self.dlg.lineEditToponyme.setText("")
            self.dlg.lineEditIdPE.setText("")
            self.dlg.lineEditIdBCAE.setText("")
            self.initbtnclic(self.listBtnTotal)
            self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[2])
            self.dlg.lineEditIdPE.setStyleSheet(CUSTOM_WIDGETS[2])
            self.dlg.lineEditIdBCAE.setStyleSheet(CUSTOM_WIDGETS[2])
            self.dlg.pushButtonPlusCourt.setEnabled(True)

        else:
            # tous les btn avec fond par defaut
            self.dlg.lineEditCleabs.setText("")
            self.dlg.lineEditToponyme.setText("")
            self.dlg.lineEditIdPE.setText("")
            self.dlg.lineEditIdBCAE.setText("")
            self.initbtnclic(self.listBtnTotal)
            self.dlg.comboBoxNature.setStyleSheet(CUSTOM_WIDGETS[2])
            self.dlg.lineEditIdPE.setStyleSheet(CUSTOM_WIDGETS[2])
            self.dlg.lineEditIdBCAE.setStyleSheet(CUSTOM_WIDGETS[2])
            self.dlg.pushButtonPlusCourt.setEnabled(False)



    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface

        self.cheminpluscourt = None

        self.dlg = None
        self.dlgEditIdPE = None
        self.dlgEditIdBCAE = None
        self.dlgAProposDe = None

        self.actionAttributHydro = None
        self.actionAfficheSpec = None

        self.idbcae = None
        self.idinventaireBCAE = None
        self.idpe = None
        self.idinventairePE = None
        self.idposol = None
        self.idtoponyme = None
        self.idnature = None
        self.idcleabs = None

        self.selectiontotal = None
        self.dicoAttributs = {}
        self.layer = None
        self.nbselection = None
        self.listeSelection = None
        # self.isAttributsmodifiy = False

        self.projectionLayer = None
        self.projectionProjet = None

        self.iface = iface
        # self.menuIGN = None

        # sauf le combobox pour la nature
        self.listbtnNature = ["pushButtonNatureCanal", "pushButtonNatureConduitBuse", "pushButtonNatureEcoulNat"]
        self.listbtnpossol = ["pushButtonPosSolm1", "pushButtonPosSol0", "pushButtonPosSol1"]
        self.listInvPE = ["pushButtonInventPEVrai", "pushButtonInventPEFaux", "pushButtonInventPEEnCours"]
        self.listInvBCAE = ["pushButtonInventBCAEVrai", "pushButtonInventBCAEFaux"]

        self.listBtnTotal = self.listbtnNature.copy()
        self.listBtnTotal += self.listbtnpossol.copy()
        self.listBtnTotal += self.listInvPE.copy()
        self.listBtnTotal += self.listInvBCAE.copy()

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'changeAttribut_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)


        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = True


    def initGui(self):
        pass


    def unload(self):
        pass


    def run(self):
        """Run method that performs all the real work"""
        if not QgsProject.instance().fileName():
            afficheerreur("Veuillez charger un projet")
            return

        # self.layer = self.iface.activeLayer()
        if not self.set_activeLayerHydro():
            afficheerreur(f"La couche \"{LAYER_HYDRO}\" n'a pas été trouvée.",TITRE_INTERFACE)
            return
        else:
            self.layer = self.iface.activeLayer()

        self.projectionLayer = self.layer.crs()
        projet = QgsProject.instance()
        self.projectionProjet = projet.crs()

        self.idcleabs = self.layer.fields().indexFromName(CLEABS)
        self.idnature = self.layer.fields().indexFromName(NATURE)
        self.idtoponyme = self.layer.fields().indexFromName(CPX_TOPONYME)
        self.idposol = self.layer.fields().indexFromName(POS_SOL)
        self.idinventairePE = self.layer.fields().indexFromName(INVENT_PE)
        self.idpe = self.layer.fields().indexFromName(ID_PE)
        self.idinventaireBCAE = self.layer.fields().indexFromName(INVENT_BCAE)
        self.idbcae = self.layer.fields().indexFromName(ID_BCAE)

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = changeAttributDialog()

            self.cheminpluscourt = cheminpluscourt(self.iface, self.layer)

            # couleur de le selection
            self.dlg.mColorButton.setColor(self.iface.mapCanvas().selectionColor())
            self.dlg.mColorButton.colorChanged.connect(self.colorchange)

            self.dlgAProposDe = Aproposde()
            self.dlgAProposDe.setWindowFlags(Qt.WindowStaysOnTopHint|Qt.WindowTitleHint | Qt.WindowCloseButtonHint)
            self.dlgAProposDe.setWindowTitle(f"{TITRE_INTERFACE} {VERSION}")

            self.dlgEditIdPE = EditIDPE()
            # self.dlgEditIdPE.setStyleSheet(FOND_DIAL)
            self.dlgEditIdPE.pushButtonOK.clicked.connect(self.recup_id_pe)
            self.dlgEditIdPE.pushButtonAnnuler.clicked.connect(self.ferme_dial)

            self.dlgEditIdBCAE = EditIDBCAE()
            # self.dlgEditIdBCAE.setStyleSheet(FOND_DIAL)
            self.dlgEditIdBCAE.pushButtonOK.clicked.connect(self.recup_id_bcae)
            self.dlgEditIdBCAE.pushButtonAnnuler.clicked.connect(self.ferme_dial)

            self.dlg.setWindowTitle(f"{TITRE_INTERFACE} {VERSION}")
            self.initialiselabel()

            # evenement de changement de selection pour actualiser la selection des Qcombobox
            self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)

            # evenement combobox
            self.dlg.comboBoxNature.currentTextChanged.connect(self.comboboxNatureChange)

            """
            evenement modif linedit
            """
            # textchange pour actuver ou non le bouton valider transaction
            # self.dlg.lineEditIdPE.textChanged.connect(self.textchangeidentPE)
            # pour recuperer la valeur du linedit , qd le linedit perd le focus
            # self.dlg.lineEditIdPE.editingFinished.connect(self.fineditionidentPE)
            # self.dlg.lineEditIdPE.returnPressed.connect(self.returnpressIdPE)

            # self.dlg.lineEditIdBCAE.textChanged.connect(self.textchangeidentBCAE)
            # self.dlg.lineEditIdBCAE.editingFinished.connect(self.fineditionidentBCAE)

            for val in LISTVALEURNATURE:
                self.dlg.comboBoxNature.addItem(val)

            # clear ici, sinon la nature du combobox est prise en compte dans tous les cas
            self.dicoAttributs.clear()
            self.actualiserSelection()

            # bouton valider la transaction
            self.dlg.pushButtonValiderTransaction.clicked.connect(self.validerLaTransaction)
            self.dlg.pushButtonValiderTransaction.setEnabled(False)
            # self.dlg.pushButtonValiderTransaction.setStyleSheet("QPushButton:hover{color:black}")
            self.dlg.pushButtonValiderTransaction.setStyleSheet(CUSTOM_WIDGETS[4])

            # bouton chemin le plus court
            self.dlg.pushButtonPlusCourt.clicked.connect(self.runchepluscourt)

            # bouton edition des Id PE ET BCAE
            self.dlg.pushButtonEditPE.clicked.connect(self.afficheDialEditIdPE)
            self.dlg.pushButtonEditBCAE.clicked.connect(self.afficheDialEditIdBCAE)

            # bouton a propos de
            self.dlg.pushButtonAProposeDe.clicked.connect(self.afficheAProposeDe)
            # bouton afficher la doc
            self.dlgAProposDe.pushButtonAffichedoc.clicked.connect(afficheDoc)

            self.dlg.pushButtonNatureCanal.clicked.connect(self.natureCanal)
            self.dlg.pushButtonNatureConduitBuse.clicked.connect(self.natureConduitBuse)
            self.dlg.pushButtonNatureEcoulNat.clicked.connect(self.natureEcoulNat)

            self.dlg.pushButtonPosSolm1.clicked.connect(self.possolmoins1)
            self.dlg.pushButtonPosSol0.clicked.connect(self.possol0)
            self.dlg.pushButtonPosSol1.clicked.connect(self.possol1)

            self.dlg.pushButtonInventPEVrai.clicked.connect(self.invPEVrai)
            self.dlg.pushButtonInventPEFaux.clicked.connect(self.invPEFaux)
            self.dlg.pushButtonInventPEEnCours.clicked.connect(self.invPEEnCours)

            self.dlg.pushButtonInventBCAEVrai.clicked.connect(self.invBCAEVrai)
            self.dlg.pushButtonInventBCAEFaux.clicked.connect(self.invBCAEFaux)

        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()
        # # See if OK was pressed
        if result == 0:
            self.dlgAProposDe.close()




